/*
 * This file is generated by jOOQ.
 */
package eu.profinit.smartplans.db.tables.records;


import eu.profinit.smartplans.db.tables.Transaction;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionRecord extends UpdatableRecordImpl<TransactionRecord> implements Record14<Long, LocalDate, BigDecimal, String, Integer, BigDecimal, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 909644422;

    /**
     * Setter for <code>public.transaction.transaction_id</code>.
     */
    public void setTransactionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.transaction.transaction_id</code>.
     */
    public Long getTransactionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.transaction.tx_date</code>.
     */
    public void setTxDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.transaction.tx_date</code>.
     */
    public LocalDate getTxDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.transaction.client_id</code>.
     */
    public void setClientId(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.transaction.client_id</code>.
     */
    public BigDecimal getClientId() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.transaction.client_gender</code>.
     */
    public void setClientGender(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.transaction.client_gender</code>.
     */
    public String getClientGender() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.transaction.client_year_of_birth</code>.
     */
    public void setClientYearOfBirth(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.transaction.client_year_of_birth</code>.
     */
    public Integer getClientYearOfBirth() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.transaction.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.transaction.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.transaction.merchant_uid</code>.
     */
    public void setMerchantUid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.transaction.merchant_uid</code>.
     */
    public String getMerchantUid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.transaction.merchant_category</code>.
     */
    public void setMerchantCategory(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.transaction.merchant_category</code>.
     */
    public String getMerchantCategory() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.transaction.shop_tags</code>.
     */
    public void setShopTags(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.transaction.shop_tags</code>.
     */
    public String getShopTags() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.transaction.merchant_category_id</code>.
     */
    public void setMerchantCategoryId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.transaction.merchant_category_id</code>.
     */
    public String getMerchantCategoryId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.transaction.shop_uid</code>.
     */
    public void setShopUid(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.transaction.shop_uid</code>.
     */
    public String getShopUid() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.transaction.shop_type</code>.
     */
    public void setShopType(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.transaction.shop_type</code>.
     */
    public String getShopType() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.transaction.region</code>.
     */
    public void setRegion(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.transaction.region</code>.
     */
    public String getRegion() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.transaction.country</code>.
     */
    public void setCountry(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.transaction.country</code>.
     */
    public String getCountry() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, LocalDate, BigDecimal, String, Integer, BigDecimal, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, LocalDate, BigDecimal, String, Integer, BigDecimal, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Transaction.TRANSACTION.TRANSACTION_ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return Transaction.TRANSACTION.TX_DATE;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Transaction.TRANSACTION.CLIENT_ID;
    }

    @Override
    public Field<String> field4() {
        return Transaction.TRANSACTION.CLIENT_GENDER;
    }

    @Override
    public Field<Integer> field5() {
        return Transaction.TRANSACTION.CLIENT_YEAR_OF_BIRTH;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Transaction.TRANSACTION.AMOUNT;
    }

    @Override
    public Field<String> field7() {
        return Transaction.TRANSACTION.MERCHANT_UID;
    }

    @Override
    public Field<String> field8() {
        return Transaction.TRANSACTION.MERCHANT_CATEGORY;
    }

    @Override
    public Field<String> field9() {
        return Transaction.TRANSACTION.SHOP_TAGS;
    }

    @Override
    public Field<String> field10() {
        return Transaction.TRANSACTION.MERCHANT_CATEGORY_ID;
    }

    @Override
    public Field<String> field11() {
        return Transaction.TRANSACTION.SHOP_UID;
    }

    @Override
    public Field<String> field12() {
        return Transaction.TRANSACTION.SHOP_TYPE;
    }

    @Override
    public Field<String> field13() {
        return Transaction.TRANSACTION.REGION;
    }

    @Override
    public Field<String> field14() {
        return Transaction.TRANSACTION.COUNTRY;
    }

    @Override
    public Long component1() {
        return getTransactionId();
    }

    @Override
    public LocalDate component2() {
        return getTxDate();
    }

    @Override
    public BigDecimal component3() {
        return getClientId();
    }

    @Override
    public String component4() {
        return getClientGender();
    }

    @Override
    public Integer component5() {
        return getClientYearOfBirth();
    }

    @Override
    public BigDecimal component6() {
        return getAmount();
    }

    @Override
    public String component7() {
        return getMerchantUid();
    }

    @Override
    public String component8() {
        return getMerchantCategory();
    }

    @Override
    public String component9() {
        return getShopTags();
    }

    @Override
    public String component10() {
        return getMerchantCategoryId();
    }

    @Override
    public String component11() {
        return getShopUid();
    }

    @Override
    public String component12() {
        return getShopType();
    }

    @Override
    public String component13() {
        return getRegion();
    }

    @Override
    public String component14() {
        return getCountry();
    }

    @Override
    public Long value1() {
        return getTransactionId();
    }

    @Override
    public LocalDate value2() {
        return getTxDate();
    }

    @Override
    public BigDecimal value3() {
        return getClientId();
    }

    @Override
    public String value4() {
        return getClientGender();
    }

    @Override
    public Integer value5() {
        return getClientYearOfBirth();
    }

    @Override
    public BigDecimal value6() {
        return getAmount();
    }

    @Override
    public String value7() {
        return getMerchantUid();
    }

    @Override
    public String value8() {
        return getMerchantCategory();
    }

    @Override
    public String value9() {
        return getShopTags();
    }

    @Override
    public String value10() {
        return getMerchantCategoryId();
    }

    @Override
    public String value11() {
        return getShopUid();
    }

    @Override
    public String value12() {
        return getShopType();
    }

    @Override
    public String value13() {
        return getRegion();
    }

    @Override
    public String value14() {
        return getCountry();
    }

    @Override
    public TransactionRecord value1(Long value) {
        setTransactionId(value);
        return this;
    }

    @Override
    public TransactionRecord value2(LocalDate value) {
        setTxDate(value);
        return this;
    }

    @Override
    public TransactionRecord value3(BigDecimal value) {
        setClientId(value);
        return this;
    }

    @Override
    public TransactionRecord value4(String value) {
        setClientGender(value);
        return this;
    }

    @Override
    public TransactionRecord value5(Integer value) {
        setClientYearOfBirth(value);
        return this;
    }

    @Override
    public TransactionRecord value6(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public TransactionRecord value7(String value) {
        setMerchantUid(value);
        return this;
    }

    @Override
    public TransactionRecord value8(String value) {
        setMerchantCategory(value);
        return this;
    }

    @Override
    public TransactionRecord value9(String value) {
        setShopTags(value);
        return this;
    }

    @Override
    public TransactionRecord value10(String value) {
        setMerchantCategoryId(value);
        return this;
    }

    @Override
    public TransactionRecord value11(String value) {
        setShopUid(value);
        return this;
    }

    @Override
    public TransactionRecord value12(String value) {
        setShopType(value);
        return this;
    }

    @Override
    public TransactionRecord value13(String value) {
        setRegion(value);
        return this;
    }

    @Override
    public TransactionRecord value14(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public TransactionRecord values(Long value1, LocalDate value2, BigDecimal value3, String value4, Integer value5, BigDecimal value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionRecord
     */
    public TransactionRecord() {
        super(Transaction.TRANSACTION);
    }

    /**
     * Create a detached, initialised TransactionRecord
     */
    public TransactionRecord(Long transactionId, LocalDate txDate, BigDecimal clientId, String clientGender, Integer clientYearOfBirth, BigDecimal amount, String merchantUid, String merchantCategory, String shopTags, String merchantCategoryId, String shopUid, String shopType, String region, String country) {
        super(Transaction.TRANSACTION);

        set(0, transactionId);
        set(1, txDate);
        set(2, clientId);
        set(3, clientGender);
        set(4, clientYearOfBirth);
        set(5, amount);
        set(6, merchantUid);
        set(7, merchantCategory);
        set(8, shopTags);
        set(9, merchantCategoryId);
        set(10, shopUid);
        set(11, shopType);
        set(12, region);
        set(13, country);
    }
}
