server:
  port: 8080
  servlet:
    context-path: /api

spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://smartplans.postgres.database.azure.com:5432/smartplans
    username: smartplans@smartplans
    password: D71PLU!6B7Px!Lpn0#hh

management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown.enabled: true
  server:
    port: 8090
