/*
 * This file is generated by jOOQ.
 */
package eu.profinit.smartplans.db.routines;


import eu.profinit.smartplans.db.Public;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatStatementsReset extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -4321856;

    /**
     * Create a new routine call instance
     */
    public PgStatStatementsReset() {
        super("pg_stat_statements_reset", Public.PUBLIC);
    }
}
